version: '3.8'

services:
  app:
    build: .
    container_name: booktracker-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:${DATABASE_PRIVATE_URL}
      - SPRING_DATASOURCE_USERNAME=${PGUSER}
      - SPRING_DATASOURCE_PASSWORD=${PGPASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
