spring:
    datasource:
        url: jdbc:${DATABASE_PRIVATE_URL}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false