spring:
    datasource:
        url: jdbc:${DATABASE_PRIVATE_URL}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        