spring:
    datasource:
        url: jdbc:${DATABASE_PRIVATE_URL}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        name: ${PGDATABASE}
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        database: postgresql
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                

        